### ISSUE TITLE
Grid gap not appearing in Markbot screenshots and unexpected duplicate display issue

### ISSUE THREAD

**Issue by briannaneet** [briannaneet/components-on-a-grid#2]
@hellachella @mackenzierose

I'm having an issue where my website looks like it matches the screenshot in both firefox and chrome, but on Markbot the grid-gap doesn't appear at all. 

Chrome:
<img width="1280" alt="chrome" src="https://user-images.githubusercontent.com/55240989/93967647-aa458c00-fd35-11ea-8038-79eb37670643.png">

Firefox:
<img width="1003" alt="firefox" src="https://user-images.githubusercontent.com/55240989/93967649-aca7e600-fd35-11ea-8792-0f77669b5238.png">

Markbot:
<img width="998" alt="markbot" src="https://user-images.githubusercontent.com/55240989/93967653-af0a4000-fd35-11ea-8fba-abc39e0d88a8.png">

I'm also having an issue where Markbot is unpleased that I've used both display: contents; and display: grid in the header, but when I remove one of them everything breaks and I'm not sure how to work around this.

I understand this is late, but I would still like to understand why and how to fix these issues :)

**Comment by MacKenzieRose** [comment]
Hey! 

### **re: gap issues**

So conceptually, what your code has told the browser (and Markbot, which you can think of as a basic browser when it renders screenshots), is to put a gap between the boxes you've outlined in your `grid-template-areas` (line 35). However, you'll notice that you only have 2 boxes (box1 and box2), so the only gap that is rendered in Markbot is the one you see (the horizontal one).

But then why do you still see a gap in your REAL browsers, like Firefox? Let's inspect while having the grid turned on:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/19557909/94015136-75a7f380-fd7a-11ea-84e4-ffe71160378c.png">

What you can see here is that your browser is smart enough to add implicit components (the dotted lines) including the gaps. Ideally, you'd solve this by changing your `grid-template-areas` to have 3 boxes, and then assign your `figures` to their respective grid areas.

### re: display: grid vs. display: contents

`display: grid` allows you to use grid styling, including grid-template-areas etc.

`display: contents` does something similar, but it also makes the element you apply it to kind of disappear. What this allows you to do is to target children element directly in the grid. So, if you apply it to your `main` tags, you could apply `grid-area: box2;` directly to your `figure` (for example).


Let me know if that helps 🙂
